### ISSUE TITLE
Reading iPhone MOV throws File format could not be determined

### ISSUE THREAD

**Issue by rnedumpurath** [drewnoakes/metadata-extractor-dotnet#344]
Starting around iOS15, I've been getting the "File format could not be determined " exception when trying to read the metadata of a video file of a Live Photo. A Live Photo on an iPhone creates an HEIC image file as well as a video file. The video file from that package is what is throwing the exception. I'm attaching a sample video file that should recreate this exception. Tested with .NET 7 running MetadataExtractor 2.8.1.

https://github.com/drewnoakes/metadata-extractor-dotnet/assets/60277804/909ef10e-fcb9-4e62-8c5a-d5b62962450e

**Comment by HEIC-to-JPEG-Dev** [comment]
Yes, I get this as well. Apple don’t like Windows :(

I’d use this library if this was fixed, otherwise it’s of no use to me as Apple files are prolific.

I can provide video files if that helps with the development of this capability

**Comment by HEIC-to-JPEG-Dev** [comment]
I would add that “throwing an exception” is very bad for performance. If I’m getting the data for a thousand files and 20% are Apple videos, this package hits a wall performance wise. It should return a code instead. Exceptions are for unexpected errors if all goes wrong, not for known, expected things you’re checking for.

**Comment by HEIC-to-JPEG-Dev** [comment]
I think Apple are using hevc encoding now

**Comment by naughtyGitCat** [comment]
same execption on live image mov too
```
MetadataExtractor.ImageProcessingException: File format could not be determined
   at MetadataExtractor.ImageMetadataReader.ReadMetadata(Stream stream)
   at MetadataExtractor.ImageMetadataReader.ReadMetadata(String filePath)
```


https://github.com/user-attachments/assets/8d126a7f-f4fa-4ca2-88ba-06776e8c21c0

**Comment by naughtyGitCat** [comment]
@rn-89 @HEIC-to-JPEG-Dev   happens with same error, the header info changes, fix it with an `if .... else ....` to  catch this circumstance

@drewnoakes please take a notice, can you merge my pr?

**Comment by HEIC-to-JPEG-Dev** [comment]
I'm guessing the repro is dead now ?

**Comment by drewnoakes** [comment]
Thanks @naughtyGitCat for fixing this. Your PR has merged, and a new release will go out shortly.
