### ISSUE TITLE
The ':' character, hexadecimal value 0x3A, cannot be included in a name

### ISSUE THREAD

**Issue by monotore** [drewnoakes/metadata-extractor-dotnet#66]
XmlException with error message "The ':' character, hexadecimal value 0x3A, cannot be included in a name" is a very common exception when running ImageMetadataReader.ReadMetadata.

Example stacktrace:
```
   at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
   at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
   at System.Xml.Linq.XNamespace.GetName(String localName)
   at System.Xml.Linq.XName.Get(String expandedName)
   at XmpCore.Impl.ParseRdf.Rdf_ResourcePropertyElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
   at XmpCore.Impl.ParseRdf.Rdf_PropertyElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
   at XmpCore.Impl.ParseRdf.Rdf_PropertyElementList(XmpMeta xmp, XmpNode xmpParent, XElement xmlParent, Boolean isTopLevel)
   at XmpCore.Impl.ParseRdf.Rdf_NodeElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
   at XmpCore.Impl.ParseRdf.Rdf_NodeElementList(XmpMeta xmp, XmpNode xmpParent, XElement rdfRdfNode)
   at XmpCore.Impl.ParseRdf.Rdf_RDF(XmpMeta xmp, XElement rdfRdfNode)
   at XmpCore.Impl.XmpMetaParser.ParseXmlDoc(XDocument document, ParseOptions options)
   at XmpCore.Impl.XmpMetaParser.Parse(Byte[] bytes, ParseOptions options)
   at MetadataExtractor.Formats.Xmp.XmpReader.Extract(Byte[] xmpBytes)
   at MetadataExtractor.Formats.Xmp.XmpReader.ReadJpegSegments(IEnumerable`1 segments, JpegSegmentType segmentType)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.<>c.<ProcessJpegSegments>b__4_4(<>f__AnonymousType1`2 <>h__TransparentIdentifier1)
   at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.ProcessJpegSegments(IEnumerable`1 readers, IEnumerable`1 segments)
   at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.Process(Stream stream, IEnumerable`1 readers)
   at MetadataExtractor.ImageMetadataReader.ReadMetadata(Stream stream)
```

XMP when exception above:
```xml
<?xpacket begin='ï»¿' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about="uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b" xmlns:dc="http://purl.org/dc/elements/1.1/"/>
    <rdf:Description rdf:about="uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b" xmlns:xmp="http://ns.adobe.com/xap/1.0/">
      <xmp:CreateDate>2016-06-15T08:38:12.946</xmp:CreateDate>
    </rdf:Description>
    <rdf:Description rdf:about="uuid:faf5bdd5-ba3d-11da-ad31-d33d75182f1b" xmlns:dc="http://purl.org/dc/elements/1.1/">
      <dc:creator>
        <rdf:Seq xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
          <rdf:li>xxx</rdf:li>
        </rdf:Seq>
      </dc:creator>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
```

It would be nice to be able to get other metadata even if XMP in invalid.

**Comment by drewnoakes** [comment]
Thanks. There's a bug in `xmp-core-dotnet` 1.2.3. Please roll back to 1.2.2 for now. I'll get a fix out shortly.

See also drewnoakes/xmp-core-dotnet#16.
