### ISSUE TITLE
XmlException on parsing Xmp

### ISSUE THREAD

**Issue by adrianliechti** [drewnoakes/metadata-extractor-dotnet#74]
Hi all,

We notice a problem while parsing some photos. As I understand, these cameras create strange XML inside the Xmp Tags - but probably it's easier to find a workaround inside the code than motivate all customers to use a proper camera :)

Is this issue already known? Would you consider to have a look in it?
Else I will try to find time to prepare a draft of a pull request.

Thanks for a short feedback, Adrian

Exception Message in Xmp Parsing
The ':' character, hexadecimal value 0x3A, cannot be included in a name.

Sample Images:

![familie042](https://cloud.githubusercontent.com/assets/343775/20573733/8e428586-b1b1-11e6-8056-2ece5dd393e6.jpg)
![familie041](https://cloud.githubusercontent.com/assets/343775/20573734/8e449f56-b1b1-11e6-8ea4-a25acac0ae4c.jpg)

```text
System.Xml.XmlException occurred
  HResult=-2146232000
  LineNumber=0
  LinePosition=3
  Message=The ':' character, hexadecimal value 0x3A, cannot be included in a name.
  Source=System.Xml
  StackTrace:
       at System.Xml.XmlConvert.VerifyNCName(String name, ExceptionType exceptionType)
       at System.Xml.Linq.XName..ctor(XNamespace ns, String localName)
       at System.Xml.Linq.XNamespace.GetName(String localName)
       at System.Xml.Linq.XName.Get(String expandedName)
       at XmpCore.Impl.ParseRdf.Rdf_ResourcePropertyElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
       at XmpCore.Impl.ParseRdf.Rdf_PropertyElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
       at XmpCore.Impl.ParseRdf.Rdf_PropertyElementList(XmpMeta xmp, XmpNode xmpParent, XElement xmlParent, Boolean isTopLevel)
       at XmpCore.Impl.ParseRdf.Rdf_NodeElement(XmpMeta xmp, XmpNode xmpParent, XElement xmlNode, Boolean isTopLevel)
       at XmpCore.Impl.ParseRdf.Rdf_NodeElementList(XmpMeta xmp, XmpNode xmpParent, XElement rdfRdfNode)
       at XmpCore.Impl.ParseRdf.Rdf_RDF(XmpMeta xmp, XElement rdfRdfNode)
       at XmpCore.Impl.XmpMetaParser.ParseXmlDoc(XDocument document, ParseOptions options)
       at XmpCore.Impl.XmpMetaParser.Parse(Byte[] bytes, ParseOptions options)
       at MetadataExtractor.Formats.Xmp.XmpReader.Extract(Byte[] xmpBytes)
       at MetadataExtractor.Formats.Xmp.XmpReader.ReadJpegSegments(IEnumerable`1 segments, JpegSegmentType segmentType)
       at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.<>c.<ProcessJpegSegments>b__4_4(<>f__AnonymousType1`2 <>h__TransparentIdentifier1)
       at System.Linq.Enumerable.<SelectManyIterator>d__22`3.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.ProcessJpegSegments(IEnumerable`1 readers, IEnumerable`1 segments)
       at MetadataExtractor.Formats.Jpeg.JpegMetadataReader.Process(Stream stream, IEnumerable`1 readers)
       at MetadataExtractor.ImageMetadataReader.ReadMetadata(Stream stream)
...
```

**Comment by paperboyo** [comment]
Just FYI. Top image was developed using Photoshop CS5 (so it may not be the camera that is at fault (if anything). Photoshop 2015.5.1 opens the file OK without giving any warnings about errors in the metadata (as it usually does when there is a problem). I can’t figure out where exactly there seems to be a problem from the above code, so can’t check if the tag in question is correct in any of the usual places...

**Comment by drewnoakes** [comment]
Hi Adrian,

Thanks for the bug report. It's a [bug in the XMP library](https://github.com/drewnoakes/xmp-core-dotnet/issues/16), which has a fix.

Can you use the pre-release version of metadata-extractor? It includes the fix.

https://www.nuget.org/packages/MetadataExtractor/2.0.0-rc1

Alternatively, just upgrade the version of your XmpCore package to one of the 2.0.0 RCs.

Hoping to get these fixes on a stable release soon.

**Comment by adrianliechti** [comment]
thanks to both of you helping me here so fast!

I can confirm that using MetadataExtractor.2.0.0-rc1 & XmpCore.2.0.0-rc4 solves the problem.
and of course I am super happy about that!

I therefore close this ticket
tx again
